"""Add planilha_id to obras

Revision ID: 3f73fa3dbeb5
Revises: 51d1cd45edb1
Create Date: 2026-07-13 16:42:15.951134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f73fa3dbeb5'
down_revision = '51d1cd45edb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obras', sa.Column('planilha_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'obras', 'planilhas', ['planilha_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'obras', type_='foreignkey')
    op.drop_column('obras', 'planilha_id')
    # ### end Alembic commands ###
