"""Decouple planilhas from obras

Revision ID: 51d1cd45edb1
Revises: 69c00d7c3982
Create Date: 2026-07-13 16:32:04.507750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d1cd45edb1'
down_revision = '69c00d7c3982'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planilhas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('planilha_google_id', sa.String(length=255), nullable=False),
    sa.Column('nome_aba', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planilhas_id'), 'planilhas', ['id'], unique=False)
    op.create_index(op.f('ix_planilhas_nome'), 'planilhas', ['nome'], unique=False)
    op.drop_column('obras', 'planilha_google_id')
    op.drop_column('obras', 'nome_aba')
    op.add_column('uploads', sa.Column('planilha_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'uploads', 'planilhas', ['planilha_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_column('uploads', 'planilha_id')
    op.add_column('obras', sa.Column('nome_aba', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('obras', sa.Column('planilha_google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_planilhas_nome'), table_name='planilhas')
    op.drop_index(op.f('ix_planilhas_id'), table_name='planilhas')
    op.drop_table('planilhas')
    # ### end Alembic commands ###
