"""Add obra_id and automacao to planilhas

Revision ID: dfd34eaf14d5
Revises: 3f73fa3dbeb5
Create Date: 2026-07-13 16:45:51.508221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd34eaf14d5'
down_revision = '3f73fa3dbeb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('obras_planilha_id_fkey'), 'obras', type_='foreignkey')
    op.drop_column('obras', 'planilha_id')
    op.add_column('planilhas', sa.Column('automacao', sa.String(length=100), nullable=False))
    op.add_column('planilhas', sa.Column('obra_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planilhas', 'obras', ['obra_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planilhas', type_='foreignkey')
    op.drop_column('planilhas', 'obra_id')
    op.drop_column('planilhas', 'automacao')
    op.add_column('obras', sa.Column('planilha_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('obras_planilha_id_fkey'), 'obras', 'planilhas', ['planilha_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
